// File templates for multi-page wiki generation.
//
// Generates ALL of:
//   - site.config.js                (with auto-populated sidebar)
//   - wiki/<homepageSlug>.md        (bio, en)
//   - wiki/<homepageSlug>.zh.md     (bio, zh) — if any zh content
//   - wiki/<projectSlug>.md         (per shipped[] item with body)
//   - wiki/<projectSlug>.zh.md      (per shipped[] item with body_zh)
//   - wiki/<eduSlug>.md/.zh.md      (per educations[] item)
//   - wiki/<expSlug>.md/.zh.md      (per experiences[] item)
//   - wiki/index.md                 (auto-generated category index)
//   - README.md
//
// Each entity page gets its own infobox + body. The bio's See also
// section is auto-populated with real slugs from the payload (replaces
// the [[Project_One]] placeholders the original template had).

const j = (v) => JSON.stringify(v ?? "");

// YAML 1.2 is a strict superset of JSON — any JSON-encoded string is a
// legal YAML double-quoted scalar. Using JSON.stringify covers \n, \r,
// \t, ", \\, control chars, and unicode in one shot, which closes the
// "newline + --- in user content escapes frontmatter" hole the previous
// hand-rolled escape had. Returns the string WITH outer quotes — caller
// emits `key: ${yamlScalar(value)}` (no manual quoting).
const yamlScalar = (s) => JSON.stringify(String(s ?? ""));

// HTML entity escape for any text that lands inside an HTML attribute
// or element body (used in the `html:` infobox rows that the wiki
// renderer treats as raw HTML). Escapes &, <, >, ", '.
const htmlEscape = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

// URL allowlist — only http(s) survives. Anything else (javascript:,
// data:, vbscript:, mailto:, etc.) is dropped to prevent XSS sinks in
// `<a href="...">`. Returns "" on rejection so callers can render a
// label-only fallback without breaking layout.
const safeHttpUrl = (s) => {
  const t = String(s ?? "").trim();
  return /^https?:\/\//i.test(t) ? t : "";
};

// Wikilink display text — strip `|` and `]` so user-controlled
// `name`/`name_zh` can't break out of `[[Slug|Display]]` syntax,
// AND escape `<` / `>` so an attacker name `School<script>...</script>`
// can't inject raw HTML into markdown body. Renderers with rehype-raw
// would otherwise treat that as live DOM. Also strips newlines so a
// multiline name doesn't break the bullet line.
const wikilinkDisplay = (s) =>
  String(s ?? "")
    .replace(/\|/g, "/")
    .replace(/\]/g, "")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/[\r\n]+/g, " ");

// Single-line text for markdown lead sentences (titleName, tagline
// inlined into body). Strip newlines + HTML-meta chars so a multi-line
// tagline doesn't shred the lead sentence and a hostile tagline can't
// inject raw HTML into the body.
const inlineMarkdownText = (s) =>
  String(s ?? "")
    .replace(/[\r\n]+/g, " ")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const stripWikilinks = (s) =>
  String(s ?? "").replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, t, l) =>
    (l || t).replace(/_/g, " ")
  );

// --- siteConfig with auto-populated sidebar ---------------------

export function siteConfigTemplate(data) {
  const siteName = data.siteName || "Yourpedia";
  const shipped = (data.shipped || []).filter((s) => s.name);
  const educations = (data.educations || []).filter((e) => e.name);
  const experiences = (data.experiences || []).filter((e) => e.name);

  const sidebarItem = (entity) =>
    `      { slug: ${j(entity.slug || "")}, label: ${j(entity.name)} }`;
  const sidebarItemZh = (entity) =>
    `      { slug: ${j(entity.slug || "")}, label: ${j(
      entity.name_zh || entity.name
    )} }`;

  const sidebarEnSection = (heading, items) =>
    `    {\n      heading: ${j(heading)},\n      items: [\n${items
      .map(sidebarItem)
      .join(",\n")}\n      ],\n    }`;
  const sidebarZhSection = (heading, items) =>
    `    {\n      heading: ${j(heading)},\n      items: [\n${items
      .map(sidebarItemZh)
      .join(",\n")}\n      ],\n    }`;

  return `// Generated by Yourpedia on ${new Date().toISOString().slice(0, 10)}.
// Edit any value below; redeploy to see changes.

export const siteConfig = {
  siteName: ${j(siteName)},
  siteTagline: {
    en: "The Free Résumé",
    zh: "自由的个人百科",
  },

  homepageSlug: ${j(data.homepageSlug)},

  meta: {
    title: ${j(`${data.name} — ${siteName}`)},
    description: ${j(data.tagline || `Biographical article on ${data.name}.`)},
    ogType: "profile",
    baseUrl: ${j(data.metaBaseUrl)},
  },

  github: {
    owner: ${j(data.githubOwner)},
    repo: ${j(data.githubRepo)},
  },

  contact: {
    email: ${j(data.email || "")},
    linkedin: ${j(data.linkedin || "")},
    githubProfile: ${j(data.githubProfile || "")},
  },

  sidebar: {
    en: [
${sidebarEnSection("Notable works", shipped)},
${sidebarEnSection("Experience", experiences)},
${sidebarEnSection("Education", educations)},
    ],
    zh: [
${sidebarZhSection("代表作品", shipped)},
${sidebarZhSection("工作经历", experiences)},
${sidebarZhSection("教育背景", educations)},
    ],
  },

  footerEdited: {
    en: "This page is maintained by its author. See GitHub for the true edit history.",
    zh: "本页面由作者本人维护。详细修订记录见 GitHub。",
  },
};

export default siteConfig;
`;
}

// --- bio page (the homepage) ------------------------------------

export function wikiPageTemplate(data, { photoPath, lang = "en" } = {}) {
  const isZh = lang === "zh";

  const titleName = isZh && data.name_zh ? data.name_zh : data.name;
  const tagline =
    (isZh ? data.tagline_zh : data.tagline) ||
    (isZh ? "[一句话定位]" : "[your one-line subtitle]");
  const bio =
    (isZh ? data.bio_zh : data.bio) ||
    (isZh
      ? `用第三人称中文 Wikipedia 风格写。用 [[Project_One]] 语法链接到其他 wiki 页面 — 还没创建的页面会渲染成红链。`
      : `Write your story in prose, Wikipedia-style. Use the third person. Link to other wiki pages with [[Project_One]] syntax. Pages that don't exist yet render as red links — a Wikipedia convention for "this article is coming."`);

  // Inline-styled thumbnail keeps rendering self-contained — no
  // dependency on colarpedia-template CSS — so /api/deploy output,
  // the zip path, and PreviewModal all render identically.
  const thumbStyle =
    "width:64px;height:64px;object-fit:cover;border-radius:4px;vertical-align:middle;margin-right:10px;border:1px solid #c8ccd1;";
  const pathExt = (p) =>
    p ? String(p).split("?")[0].split("#")[0].split(".").pop().toLowerCase() : "";

  const shippedList = (data.shipped || [])
    .filter((s) => s.name)
    .map((s) => {
      const desc = isZh ? (s.description_zh || s.description) : s.description;
      const ext = pathExt(s.thumbnailPath);
      const isPdf = ext === "pdf";
      const isImage = !!s.thumbnailPath && !isPdf;

      const prefix = isImage
        ? `<img src="${s.thumbnailPath}" alt="" style="${thumbStyle}" /> `
        : "";
      const suffix = isPdf
        ? ` ([${isZh ? "PDF 文件" : "PDF"}](${s.thumbnailPath}))`
        : "";

      const displayName = isZh && s.name_zh ? s.name_zh : s.name;
      const linkedName = s.slug
        ? `[[${s.slug}|${wikilinkDisplay(displayName)}]]`
        : `**${displayName}**`;
      const main = desc ? `${linkedName} — ${desc}` : linkedName;
      return `- ${prefix}${main}${suffix}`;
    })
    .join("\n");

  // ---- Infobox rows ----
  const knownForLabel = isZh ? "以…著称" : "Known for";
  const contactLabel = isZh ? "联系方式" : "Contact";

  const rows = [];
  // Yourpedia is a career/work wiki — we deliberately omit personal
  // metadata (Born / Nationality / Residence / Occupations). HR doesn't
  // need that and it bloats output tokens for no benefit.
  if (data.name_zh && !isZh) {
    rows.push(`    - label: Other names`);
    rows.push(`      value: ${yamlScalar(data.name_zh)}`);
  }
  // Education (cross-link to school pages). All user-controlled strings
  // pass through htmlEscape; slugs come pre-validated from the server.
  const educationsArr = (data.educations || []).filter((e) => e.name);
  if (educationsArr.length) {
    const html = educationsArr
      .map((e) => {
        const display = htmlEscape(isZh && e.name_zh ? e.name_zh : e.name);
        const degree = htmlEscape(isZh ? e.degree_zh || "" : e.degree || "");
        const slug = e.slug || "";
        const linked = slug
          ? `<a href="/wiki/${slug}/">${display}</a>`
          : display;
        return degree ? `${linked} (${degree})` : linked;
      })
      .join("<br/>");
    rows.push(`    - label: ${isZh ? "教育背景" : "Education"}`);
    // The whole block is a YAML scalar — yamlScalar handles ", \, \n inside.
    rows.push(`      html: ${yamlScalar(html)}`);
  }
  // Known for (tagline)
  rows.push(`    - label: ${knownForLabel}`);
  rows.push(`      value: ${yamlScalar(tagline)}`);
  // Contact section. URL fields go through safeHttpUrl (drops javascript:,
  // data:, mailto:, etc.); display text + URL both htmlEscape'd before
  // landing in <a href>.
  const contactRows = [];
  if (data.email) {
    contactRows.push(`    - label: ${isZh ? "邮箱" : "Email"}`);
    contactRows.push(`      value: ${yamlScalar(data.email)}`);
  }
  const linkedinUrl = safeHttpUrl(data.linkedin);
  if (linkedinUrl) {
    const display = htmlEscape(
      linkedinUrl.replace(/^https?:\/\/(www\.)?/, "")
    );
    contactRows.push(`    - label: LinkedIn`);
    contactRows.push(
      `      html: ${yamlScalar(`<a href="${htmlEscape(linkedinUrl)}">${display}</a>`)}`
    );
  }
  const githubUrl = safeHttpUrl(data.githubProfile);
  if (githubUrl) {
    const display = htmlEscape(
      githubUrl.replace(/^https?:\/\/(www\.)?/, "")
    );
    contactRows.push(`    - label: GitHub`);
    contactRows.push(
      `      html: ${yamlScalar(`<a href="${htmlEscape(githubUrl)}">${display}</a>`)}`
    );
  }
  if (contactRows.length) {
    rows.push(`    - section: ${contactLabel}`);
    rows.push(...contactRows);
  }

  const imageBlock = photoPath
    ? `\n  image: /${photoPath.replace(/^public\//, "")}\n  image_caption: ${yamlScalar(
        (isZh ? "照片:" : "Photo of ") + titleName
      )}`
    : `\n  image_caption: ${yamlScalar(
        isZh
          ? "把你的照片放到 /public/portrait.jpg"
          : "Replace /public/portrait.jpg with your photo"
      )}`;

  const description = isZh
    ? `关于 ${titleName} 的人物条目。`
    : `Biographical article on ${titleName}.`;

  // English lead sentence wraps with article ("a"/"an"); Chinese uses 是 + 复读 tagline.
  const safeTitle = inlineMarkdownText(titleName);
  const safeTag = inlineMarkdownText(tagline);
  const leadSentence = isZh
    ? `**${safeTitle}** 是${safeTag}。`
    : `**${safeTitle}** is ${
        safeTag.toLowerCase().startsWith("a ") ||
        safeTag.toLowerCase().startsWith("an ")
          ? safeTag
          : `a ${safeTag}`
      }.`;

  // ---- Sections ----
  const careerHeading = isZh ? "## 生涯" : "## Career";
  const educationHeading = isZh ? "## 教育" : "## Education";
  const notableHeading = isZh ? "## 代表作品" : "## Notable works";
  const seeAlsoHeading = isZh ? "## 参见" : "## See also";
  const referencesHeading = isZh ? "## 参考文献" : "## References";

  // Education narrative: compose from educations[] entries (one-liner per
  // school, with cross-link). User can rewrite this section by hand.
  let educationSection = "";
  if (educationsArr.length) {
    const lines = educationsArr.map((e) => {
      const eduDisplay = isZh && e.name_zh ? e.name_zh : e.name;
      const linked = e.slug
        ? `[[${e.slug}|${wikilinkDisplay(eduDisplay)}]]`
        : eduDisplay;
      const degree = isZh ? e.degree_zh : e.degree;
      const dates = e.date_range ? ` (${e.date_range})` : "";
      return degree ? `- ${linked} — ${degree}${dates}` : `- ${linked}${dates}`;
    });
    educationSection = `${educationHeading}\n\n${lines.join("\n")}\n\n`;
  }

  // See also: real slugs from the payload (not [[Project_One]] placeholders)
  const seeAlsoSlugs = [
    ...(data.shipped || []).map((s) => s.slug).filter(Boolean),
    ...(data.experiences || []).map((e) => e.slug).filter(Boolean),
    ...(data.educations || []).map((e) => e.slug).filter(Boolean),
  ];
  const seeAlsoBlock = seeAlsoSlugs.length
    ? seeAlsoSlugs.map((s) => `- [[${s}]]`).join("\n")
    : isZh
    ? "- _(尚无相关条目)_"
    : "- _(no cross-references yet)_";

  const referenceFootnote = isZh
    ? `[^1]: 用真实的引用替换此处。可用 LinkedIn 帖子、App Store 列表、项目 URL、公开发表的文章等。`
    : `[^1]: Replace this with a real citation. LinkedIn posts, App Store
listings, product URLs, and published articles all work.`;

  return `---
title: ${yamlScalar(titleName)}
subtitle: ${yamlScalar(tagline)}
description: ${yamlScalar(description)}
infobox:
  title: ${yamlScalar(titleName)}${imageBlock}
  rows:
${rows.join("\n")}
---

${leadSentence}

${careerHeading}

${bio}

${educationSection}${shippedList ? `${notableHeading}\n\n${shippedList}\n\n` : ""}${seeAlsoHeading}

${seeAlsoBlock}

${referencesHeading}

${referenceFootnote}
`;
}

// --- per-project page -------------------------------------------

export function projectPageTemplate(project, ctx, { lang = "en" } = {}) {
  const isZh = lang === "zh";
  const homepageSlug = ctx?.homepageSlug || "";
  const personName =
    isZh && ctx?.name_zh ? ctx.name_zh : ctx?.name || "[author]";

  const title =
    isZh && project.name_zh ? `${project.name_zh} (${project.name})` : project.name;
  const subtitle =
    (isZh ? project.description_zh : project.description) || "";
  const description = isZh
    ? `关于 ${project.name} 项目的条目。`
    : `Article on the project ${project.name}.`;

  const rows = [];
  rows.push(`    - label: ${isZh ? "类型" : "Type"}`);
  rows.push(`      value: ${isZh ? "项目" : "Project"}`);
  if (project.role) {
    rows.push(`    - label: ${isZh ? "角色" : "Role"}`);
    rows.push(`      value: ${yamlScalar(isZh ? project.role_zh || project.role : project.role)}`);
  }
  if (project.date_range) {
    rows.push(`    - label: ${isZh ? "时间" : "Dates"}`);
    rows.push(`      value: ${yamlScalar(project.date_range)}`);
  }
  const projectUrl = safeHttpUrl(project.url);
  if (projectUrl) {
    const display = htmlEscape(
      projectUrl.replace(/^https?:\/\/(www\.)?/, "")
    );
    rows.push(`    - label: URL`);
    rows.push(
      `      html: ${yamlScalar(`<a href="${htmlEscape(projectUrl)}">${display}</a>`)}`
    );
  }
  if (Array.isArray(project.tech_stack) && project.tech_stack.length) {
    rows.push(`    - label: ${isZh ? "技术栈" : "Tech stack"}`);
    rows.push(`      value: ${yamlScalar(project.tech_stack.join(", "))}`);
  }
  if (homepageSlug) {
    rows.push(`    - label: ${isZh ? "作者" : "Creator"}`);
    rows.push(
      `      html: ${yamlScalar(`<a href="/wiki/${homepageSlug}/">${htmlEscape(personName)}</a>`)}`
    );
  }

  const safeProjectName = inlineMarkdownText(project.name_zh || project.name);
  const safeProjectNameEn = inlineMarkdownText(project.name);
  const safeSubtitle = inlineMarkdownText(subtitle);
  const linkedPerson = homepageSlug
    ? `[[${homepageSlug}|${wikilinkDisplay(personName)}]]`
    : inlineMarkdownText(personName);
  const lead = isZh
    ? `**${safeProjectName}** 是 ${linkedPerson} 的项目${safeSubtitle ? `,${safeSubtitle}` : ""}。`
    : `**${safeProjectNameEn}** is a project by ${linkedPerson}${safeSubtitle ? `, ${safeSubtitle}` : ""}.`;

  const body = isZh
    ? project.body_zh ||
      `_(此页面正在等待详细内容。可在 \`wiki/${project.slug || project.name}.zh.md\` 中编辑。)_`
    : project.body ||
      `_(This page awaits detailed content. Edit \`wiki/${project.slug || project.name}.md\` to fill it in.)_`;

  const seeAlsoHeading = isZh ? "## 参见" : "## See also";
  const referencesHeading = isZh ? "## 参考文献" : "## References";
  const referenceFootnote = isZh
    ? `[^1]: 替换为真实引用。`
    : `[^1]: Replace this with a real citation.`;

  return `---
title: ${yamlScalar(title)}
subtitle: ${yamlScalar(subtitle)}
description: ${yamlScalar(description)}
infobox:
  title: ${yamlScalar(project.name)}
  rows:
${rows.join("\n")}
---

${lead}

${body}

${seeAlsoHeading}

${homepageSlug ? `- [[${homepageSlug}]]` : `- _(尚无相关条目)_`}

${referencesHeading}

${referenceFootnote}
`;
}

// --- per-institution page (education or experience) -----------

export function institutionPageTemplate(entity, ctx, kind, { lang = "en" } = {}) {
  const isZh = lang === "zh";
  const homepageSlug = ctx?.homepageSlug || "";
  const personName =
    isZh && ctx?.name_zh ? ctx.name_zh : ctx?.name || "[person]";
  const isEducation = kind === "education";

  const displayName =
    isZh && entity.name_zh ? `${entity.name_zh} (${entity.name})` : entity.name;
  const subtitle = isEducation
    ? (isZh ? entity.degree_zh : entity.degree) || ""
    : (isZh ? entity.role_zh : entity.role) || "";
  const description = isZh
    ? `关于 ${entity.name} 的条目。`
    : `Article on ${entity.name}.`;

  const rows = [];
  rows.push(`    - label: ${isZh ? "类型" : "Type"}`);
  rows.push(
    `      value: ${
      isEducation ? (isZh ? "教育机构" : "Educational institution") : (isZh ? "雇主" : "Employer")
    }`
  );
  if (entity.location) {
    rows.push(`    - label: ${isZh ? "地点" : "Location"}`);
    rows.push(`      value: ${yamlScalar(entity.location)}`);
  }
  if (isEducation && (entity.degree || entity.degree_zh)) {
    rows.push(`    - label: ${isZh ? "学位" : "Degree"}`);
    rows.push(
      `      value: ${yamlScalar(isZh ? entity.degree_zh || entity.degree : entity.degree)}`
    );
  }
  if (!isEducation && (entity.role || entity.role_zh)) {
    rows.push(`    - label: ${isZh ? "职位" : "Role"}`);
    rows.push(
      `      value: ${yamlScalar(isZh ? entity.role_zh || entity.role : entity.role)}`
    );
  }
  if (entity.date_range) {
    rows.push(`    - label: ${isZh ? "时间" : "Dates"}`);
    rows.push(`      value: ${yamlScalar(entity.date_range)}`);
  }
  if (homepageSlug) {
    rows.push(
      `    - section: ${isZh ? "相关条目" : "Associated"}`
    );
    rows.push(
      `    - label: ${isZh ? "成员" : "Affiliated person"}`
    );
    rows.push(
      `      html: ${yamlScalar(`<a href="/wiki/${homepageSlug}/">${htmlEscape(personName)}</a>`)}`
    );
  }

  const linkedPerson = homepageSlug
    ? `[[${homepageSlug}|${wikilinkDisplay(personName)}]]`
    : inlineMarkdownText(personName);
  const entityNameSafe = inlineMarkdownText(entity.name_zh || entity.name);
  const entityNameEnSafe = inlineMarkdownText(entity.name);
  const lead = isEducation
    ? isZh
      ? `**${entityNameSafe}** 是 ${linkedPerson} 的母校之一。`
      : `**${entityNameEnSafe}** is one of the institutions attended by ${linkedPerson}.`
    : isZh
    ? `**${entityNameSafe}** 是 ${linkedPerson} 曾任职的雇主。`
    : `**${entityNameEnSafe}** is an employer that ${linkedPerson} has worked at.`;

  const body = isZh
    ? entity.body_zh ||
      `_(此页面正在等待详细内容。可在 \`wiki/${entity.slug || entity.name}.zh.md\` 中编辑。)_`
    : entity.body ||
      `_(This page awaits detailed content. Edit \`wiki/${entity.slug || entity.name}.md\` to fill it in.)_`;

  const seeAlsoHeading = isZh ? "## 参见" : "## See also";
  const referencesHeading = isZh ? "## 参考文献" : "## References";
  const referenceFootnote = isZh
    ? `[^1]: 替换为真实引用。`
    : `[^1]: Replace this with a real citation.`;

  return `---
title: ${yamlScalar(displayName)}
subtitle: ${yamlScalar(subtitle)}
description: ${yamlScalar(description)}
infobox:
  title: ${yamlScalar(entity.name)}
  rows:
${rows.join("\n")}
---

${lead}

${body}

${seeAlsoHeading}

${homepageSlug ? `- [[${homepageSlug}]]` : `- _(尚无相关条目)_`}

${referencesHeading}

${referenceFootnote}
`;
}

// --- index page (auto-generated category index) ------------------

export function indexPageTemplate(data, { lang = "en" } = {}) {
  const isZh = lang === "zh";
  const siteName = data.siteName || "Yourpedia";
  const personName = isZh && data.name_zh ? data.name_zh : data.name;
  const headline = isZh ? `${siteName} 索引` : `${siteName} index`;

  const sectionList = (heading, items, getLabel) => {
    const filtered = items.filter((x) => x.slug);
    if (!filtered.length) return "";
    const lines = filtered
      .map(
        (x) =>
          `- [[${x.slug}|${wikilinkDisplay(stripWikilinks(getLabel(x)))}]]`
      )
      .join("\n");
    return `## ${heading}\n\n${lines}\n`;
  };

  const bioSection = `## ${isZh ? "传记" : "Biography"}\n\n- [[${
    data.homepageSlug
  }|${wikilinkDisplay(stripWikilinks(personName))}]]\n`;

  const works = sectionList(
    isZh ? "代表作品" : "Notable works",
    data.shipped || [],
    (x) => (isZh && x.name_zh ? x.name_zh : x.name)
  );
  const exp = sectionList(
    isZh ? "工作经历" : "Experience",
    data.experiences || [],
    (x) => (isZh && x.name_zh ? x.name_zh : x.name)
  );
  const edu = sectionList(
    isZh ? "教育背景" : "Education",
    data.educations || [],
    (x) => (isZh && x.name_zh ? x.name_zh : x.name)
  );

  const description = isZh
    ? `${siteName} 的全站条目索引。`
    : `Site-wide index of articles in ${siteName}.`;

  return `---
title: ${yamlScalar(headline)}
description: ${yamlScalar(description)}
---

# ${headline}

${bioSection}
${works}
${exp}
${edu}`;
}

// --- README (deployment instructions) ---------------------------

export function readmeTemplate(
  data,
  {
    hasPhoto = false,
    hasOriginalPdf = false,
    includesTemplate = false,
    hasChinese = false,
  } = {}
) {
  const today = new Date().toISOString().slice(0, 10);
  const siteName = data.siteName || "Yourpedia";
  const photoLine = hasPhoto
    ? `- \`public/portrait.*\` — your portrait photo (already wired into the bio infobox).`
    : `- _(no portrait — the bio infobox shows a placeholder. Add your own photo at \`public/portrait.jpg\`.)_`;
  const pdfLine = hasOriginalPdf
    ? `- \`raw/<your-resume>.pdf\` — your original résumé, archived for reference.`
    : "";
  const templateLine = includesTemplate
    ? `- \`app/\`, \`components/\`, \`lib/\`, \`package.json\`, \`next.config.mjs\`, \`CLAUDE.md\`, \`LICENSE\`, etc. — the **complete Next.js template**, ready to run.`
    : "";
  const zhLine = hasChinese
    ? `- \`wiki/<Slug>.zh.md\` files for every page — Chinese (Simplified) versions.`
    : "";
  const projectsLine = (data.shipped || []).filter((s) => s.slug).length
    ? `- \`wiki/<ProjectSlug>.md\` per shipped project — standalone wiki article each.`
    : "";
  const eduLine = (data.educations || []).filter((e) => e.slug).length
    ? `- \`wiki/<SchoolSlug>.md\` per education — standalone article each.`
    : "";
  const expLine = (data.experiences || []).filter((e) => e.slug).length
    ? `- \`wiki/<EmployerSlug>.md\` per work experience — standalone article each.`
    : "";

  const deployBody = includesTemplate
    ? `## Deploy in 5 minutes (zip is a complete Next.js project)

1. **Install and run:**

   \`\`\`bash
   cd ${data.githubRepo || "your-wiki-folder"}
   npm install
   npm run dev      # → http://localhost:3000
   \`\`\`

2. **Create a new GitHub repo** at <https://github.com/new>.

3. **Push:**

   \`\`\`bash
   git init
   git add .
   git commit -m "Initial setup via Yourpedia"
   git branch -M main
   git remote add origin https://github.com/${data.githubOwner || "<your-username>"}/${data.githubRepo || "<your-repo>"}.git
   git push -u origin main
   \`\`\`

4. **Deploy on Vercel** at <https://vercel.com/new>.`
    : `## Deploy

Fork the colarpedia-template, drop these files in, push, deploy on Vercel.`;

  return `# ${data.name}'s ${siteName}

> Generated by Yourpedia on ${today}.

This is your personal Wikipedia-style wiki${includesTemplate ? ", as a self-contained Next.js project" : ""}.

## What's in this zip

- \`site.config.js\` — per-site config with auto-populated sidebar
- \`wiki/${data.homepageSlug}.md\` — bio (en)
${zhLine ? zhLine + "\n" : ""}${projectsLine ? projectsLine + "\n" : ""}${eduLine ? eduLine + "\n" : ""}${expLine ? expLine + "\n" : ""}- \`wiki/index.md\` — auto-generated category index
${photoLine}
${pdfLine ? pdfLine + "\n" : ""}${templateLine ? templateLine + "\n" : ""}- \`README.md\` — this file

${deployBody}

## Maintain it

Open the repo in any AI coding tool. The schema in \`CLAUDE.md\` (at the repo root) describes how to maintain the wiki — add pages, cross-link them, keep tone consistent.

## Credit

- Visual system: Wikipedia (Wikimedia Foundation).
- Generator: Yourpedia — open source at
  <https://github.com/wangxuzhou666-arch/colarpedia-template>.
`;
}
